### ISSUE TITLE
"Glow" Bug

### ISSUE THREAD

**Issue by LimnedMoon** [nathan-commits/realtime-weather#4]
Hey,
i notice a "glow bug" in some situations. Especially when it comes to rain with overcast and on dusk.
Then it comes to a massive ...ya kind of overblending.

* Tested with latest official Esx 1.8.5
* NO other weather sync resources
* NO Admin panels or other weather related systems

Config in server.cfg:
set weather_debugMode true
#set weather_latitude 34.0                                                       #Latitude Los Angeles-Center
#set weather_longitude -118.25                                               #Longitude Los Angeles-Center
set weather_presetLocation "Berlin"
set weather_useFahrenheit false
set weather_realtimeTime true
set weather_disableDynamic true                                              # No matter the glow bug problem

Oh and at least, is it possible there is a problem with negative lat/lons ?
I want to set to LA - because los santos is the equivalent but seems weird ?!

Best Regards

**Comment by nathan-commits** [comment]
Are you using any graphics mods?

**Comment by LimnedMoon** [comment]
No Sir, 
not Clientside,
no server graphics resources. just standard es 1.8.5 latest official release in my test enviroment.

* If it is important // Graphic ingame Settings are on VeryHigh -Ultra Mix. But thazs it

Best Regards

**Comment by nathan-commits** [comment]
Alright, thanks! Will look into this soon.

**Comment by LimnedMoon** [comment]
Hey again, is there any Progress on this issue ?

Its on every time weather changes. 
The Weather becomes sometimes crazy....

Again, theres no other resources, changes weather conditions or time, and No graphic mods. Not server-and not clientside.
Im on esx 1.8.5
you can see a screenshot whats going on sometimes.

- Sometimes its an overglow, sometimes it turnes to halloween weather etc.
- especially at night this Glow is like you look into the sun. And this Special Weather conditions are horrible ^^
![Screenshot_8](https://user-images.githubusercontent.com/17122774/201394472-ea29e641-792b-4abf-a00c-a6d0dca6105f.png)

Server-cfg entries are:
set weather_debugMode true
set weather_latitude 34.0                                           # Latitude(Breite) Los Angeles-Center
set weather_longitude -118.25                                       # Longitude(Länge) Los Angeles-Center
set weather_useFahrenheit false
set weather_realtimeTime true
set weather_disableDynamic true

**Comment by nathan-commits** [comment]
Hello,

How common is this? 

Please set the convar "weather_debugMode" to "true" to enable server debug logging. 

What's the weather type in the server console when it looks like this?

**Comment by LimnedMoon** [comment]
Good morning, 
yah, you know the debug is on since the first issue ago, i played arround with the weather types, it seems there is something "doubling" and in conflict. 
I took this to look at the types https://wiki.gtanet.work/index.php?title=Weather
As you can see it is somethin with the WEather ID 9 - there is this glowing and creepy visual glitchty stuff
The "Smoggy light rain"

Timesync is definetly well
and weathersync as it is also. 
its definetly somethin with the weather types


Regards


edit: how common ? 
well, nearby everytime when weather is changing the type
